export const PRODUCTS = [
  {
    id: 'jaecoo-5',
    brand: 'JAECOO',
    model: 'J5 HEV',
    fullName: 'JAECOO J5 HEV',
    year: 2025,
    segment: 'SUV Compact (C) — Full Hybrid',
    origin: 'Chine (Chery Group)',
    status: 'new',
    tagline: 'SUV compact Full Hybrid, efficace, connecté et accessible',
    image: null,
    colors: [
      'Khaki White (nacrée — incluse)',
      'Carbon Crystal Black (nacrée — +690 €)',
      'Bleu foncé (métallisé — +690 €)',
      'Feuilles d\'eucalyptus (métallisé — +690 €)',
      'Gris Phantom (métallisé — +690 €)',
      'Eucalyptus & Carbon Crystal Black (biton — +990 €)',
      'Khaki White & Carbon Crystal Black (biton — +990 €)',
    ],
    finitions: [
      { nom: 'Select',    prix: 27900, description: 'Sièges tissu noirs, volant similicuir' },
      { nom: 'Exclusive', prix: 30900, description: 'Sièges similicuir, ventilation sièges, audio SONY, éclairage ambiance 64 couleurs' },
    ],

    specs: {
      motorisation: '1.5TGDI Full Hybrid (HEV) — DHT',
      puissance: '165 kW — 224 ch système',
      couple: '295 Nm',
      transmission: 'DHT — Transmission hybride',
      traction: 'Traction avant (FWD)',
      cylindree: '1 499 cm³ · 4 cylindres · Turbo · Injection directe',
      norme: 'Euro 6e-B',
      batterie_kwh: 1.83,
      type_batterie: 'NCM',
      co2_wltp: 120,
      classe_co2: 'D',
      consommation: '5,3 L/100km (WLTP mixte)',
      consommation_ville: '3,9 L/100km',
      consommation_route: '4,6 L/100km',
      consommation_autoroute: '6,7 L/100km',
      autonomie_wltp: 980,
      vitesse_max: 175,
      acceleration: '7,9 s (0–100 km/h)',
      longueur: 4380,
      largeur: 1860,
      hauteur: 1650,
      empattement: 2620,
      coffre: 314,
      coffre_max: 1214,
      reservoir: 51,
      poids: 1611,
      ptac: 2044,
      charge_toit: 75,
      remorquage: '750 kg (non freinée)',
    },

    prix: {
      base: 27900,
      haut: 30900,
      devise: 'EUR',
    },

    garantie: {
      vehicule: '7 ans ou 150 000 km',
      peinture: '3 ans',
      anticorrosion: '12 ans',
      electrique: '8 ans ou 160 000 km (chaîne traction)',
      assistance: '3 ans Europe (dépannage, hébergement, véhicule de remplacement)',
    },

    equipements: [
      // Série sur les deux finitions
      'Jantes alliage 18 pouces',
      'Phares à projection LED (réglage électrique)',
      'Feux arrière LED · Follow-me-home',
      'Toit vitré panoramique',
      'Hayon à ouverture électrique (PEPS)',
      'Accès mains libres & démarrage sans clé',
      'Écran tactile central 13,2 pouces (vertical)',
      'Combiné d\'instrumentation LCD 8,88 pouces',
      'Apple CarPlay & Android Auto sans fil',
      'Commande vocale',
      'Climatisation automatique bi-zone',
      'Caméra panoramique 540°',
      'Éclairage d\'ambiance',
      'Sièges avant chauffants (assise + dossier)',
      'Volant chauffant',
      'Dossiers banquette rabattables 40:60',
      '20 aides à la conduite (AEB, ACC, LDW, BSD, RCTA…)',
      'Alerte fatigue et vigilance (DMS)',
      '7 airbags · ISOFIX (x2 arrière)',
      // Exclusive uniquement
      'Sièges avant ventilés (assise + dossier) — Exclusive',
      'Sièges avant réglables électriquement 6 positions — Exclusive',
      'Système audio premium SONY 8 HP — Exclusive',
      'Recharge smartphone sans fil 50W (refroidissement actif) — Exclusive',
      'Éclairage d\'ambiance 64 couleurs — Exclusive',
      'Rétroviseurs chauffants électriques — Exclusive',
      'Vitres arrière surteintées — Exclusive',
    ],

    concurrents: [
      { nom: 'Toyota Yaris Cross HEV', prix: 28990, co2: 102, conso: 4.7 },
      { nom: 'Renault Austral HEV',    prix: 34490, co2: 108, conso: 5.2 },
      { nom: 'Peugeot 3008 HEV',       prix: 39990, co2: 112, conso: 5.1 },
      { nom: 'Kia Sportage HEV',        prix: 36990, co2: 130, conso: 5.8 },
    ],

    btob: {
      cibles: ['Flottes PME & artisans', 'Véhicules de service', 'Auto-écoles', 'Secteur santé'],
      atouts: [
        'CO₂ 120 g/km → malus limité, TCO optimisé pour les flottes',
        'Garantie 7 ans / 150 000 km — rassurant pour les entreprises',
        'Consommation réelle très faible en usage urbain (3,9 L/100)',
        'Équipement complet de série, peu d\'options à gérer',
        'Assistance 3 ans Europe incluse',
      ],
      objections: [
        'Réseau SAV encore en développement',
        'Valeur résiduelle à confirmer sur le marché VO',
      ],
      remise_cible: '8-12%',
      argument_prix: 'Full Hybrid complet à 27 900 € — TCO imbattable sur 4 ans vs thermique comparable',
    },

    btoc: {
      cibles: ['Familles primo-accédantes', '30-50 ans urbains', 'Clients sensibles au TCO'],
      atouts: [
        'Hybrid Full : économies réelles sur le carburant',
        'CO₂ 120 g/km : malus modéré vs thermique pur',
        'Garantie 7 ans — argument rassurant marque nouvelle',
        'Équipements généreusement dotés de série',
        'Autonomie totale 980 km sans anxiété de recharge',
      ],
      objections: [
        'Marque peu connue du grand public',
        'Valeur de revente incertaine',
      ],
      argument_prix: 'Full Hybrid Sony/540°/ADAS complet à partir de 27 900 € — 6 000 € sous les équivalents japonais',
    },

    marche: {
      part_marche_cible: '1,5%',
      croissance_segment: '+11,2% en 2024 (hybrides SUV)',
      tendance: 'Le segment SUV hybrid compact explose. Les clients cherchent l\'économie du full hybrid sans contrainte de recharge.',
      risques: 'Droits de douane UE +20,7% sur les véhicules chinois depuis nov. 2024. Impact sur marge et prix.',
      opportunites: 'Positionnement prix 5-8k€ sous Toyota/Renault/Kia équivalents. CO₂ 120 g/km → malus acceptable. Garantie 7 ans différenciante.',
    },
  },

  {
    id: 'jaecoo-7',
    brand: 'JAECOO',
    model: 'J7 PHEV',
    fullName: 'JAECOO J7 PHEV',
    year: 2025,
    segment: 'SUV Grand (C/D) — Plug-in Hybrid',
    origin: 'Chine (Chery Group)',
    status: 'soon',
    tagline: 'Grand SUV PHEV, 1 200 km d\'autonomie, 5 étoiles Euro-NCAP',
    image: null,
    colors: [
      'Blanc (incluse)',
      'Gris Phantom (métallisé)',
      'Noir Crystal (nacré)',
      'Vert Eucalyptus (métallisé)',
    ],
    finitions: [
      { nom: 'Select',    prix: 38900, description: 'Sièges tissu, connectivité complète, 20 ADAS' },
      { nom: 'Exclusive', prix: 46900, description: 'Sièges cuir, audio SONY, V2L, équipements premium' },
    ],

    specs: {
      motorisation: '1.5TGDI PHEV (Plug-in Hybrid)',
      puissance: '205 kW — 279 ch système',
      couple: '365 Nm',
      transmission: 'DHT — Transmission hybride rechargeable',
      traction: 'Traction avant (FWD)',
      cylindree: '1 499 cm³ · 4 cylindres · Turbo · Injection directe',
      norme: 'Euro 6e',
      batterie_kwh: 18.3,
      type_batterie: 'LFP',
      autonomie_electrique: 75,
      co2_wltp: 35,
      classe_co2: 'A',
      consommation: '2,4 L/100km (WLTP PHEV)',
      autonomie_wltp: 1200,
      vitesse_max: 185,
      acceleration: '~7,5 s (0–100 km/h)',
      longueur: 4535,
      largeur: 1865,
      hauteur: 1720,
      empattement: 2710,
      coffre: 450,
      coffre_max: 1400,
      reservoir: 55,
      poids: 1950,
      ptac: 2430,
      charge_toit: 75,
      remorquage: '1 500 kg (freinée)',
    },

    prix: {
      base: 38900,
      haut: 46900,
      devise: 'EUR',
    },

    garantie: {
      vehicule: '7 ans ou 150 000 km',
      peinture: '3 ans',
      anticorrosion: '12 ans',
      electrique: '8 ans ou 160 000 km (chaîne traction)',
      assistance: '3 ans Europe',
    },

    equipements: [
      'Jantes alliage 19 pouces',
      'Phares à LED',
      'Toit panoramique en verre sur toute la longueur',
      'Écran LCD central 14,8 pouces',
      'Système audio SONY 8 haut-parleurs',
      'Charge rapide sans fil 50W (smartphone)',
      'Apple CarPlay & Android Auto sans fil',
      'Éclairage d\'ambiance',
      'Technologie V2L (vehicle-to-load)',
      'Commande vocale intelligente',
      'Accès sans clé',
      'Mises à jour OTA',
      '20 aides à la conduite + assistant stationnement',
      'Euro-NCAP 5 étoiles',
      'Systèmes avancés de sécurité des batteries',
      '8 airbags',
    ],

    concurrents: [
      { nom: 'Peugeot 3008 PHEV',       prix: 45990, co2: 21, conso: 1.6 },
      { nom: 'Kia Sportage PHEV',         prix: 44990, co2: 31, conso: 1.6 },
      { nom: 'Mitsubishi Outlander PHEV', prix: 47990, co2: 46, conso: 2.5 },
      { nom: 'Toyota RAV4 PHEV',          prix: 50990, co2: 22, conso: 1.8 },
    ],

    btob: {
      cibles: ['Cadres & dirigeants', 'Véhicules de direction premium', 'Flottes grandes entreprises', 'Transport de personnes'],
      atouts: [
        'CO₂ 35 g/km → exonéré de malus, avantage en nature minimal',
        '5 étoiles Euro-NCAP : argument sécurité flotte incontournable',
        '1 200 km autonomie totale : zéro anxiété pour les grands déplacements',
        'Technologie V2L : utilisation comme groupe électrogène sur chantier/events',
        'Garantie 7 ans constructeur',
      ],
      objections: [
        'Marque à évangéliser auprès des comités de direction',
        'Réseau de recharge à vérifier selon les trajets',
      ],
      remise_cible: '10-15%',
      argument_prix: 'PHEV 5★ Euro-NCAP, 14,8", V2L, 1 200 km — 8 000 € sous les équivalents européens',
    },

    btoc: {
      cibles: ['Familles avec enfants', '35-55 ans CSP+', 'Gros rouleurs cherchant économies'],
      atouts: [
        'PHEV : trajets quotidiens souvent 100% électrique',
        '5 étoiles Euro-NCAP : sécurité maximale prouvée',
        '1 200 km sans stress sur les longs trajets',
        'Écran 14,8" + SONY + V2L : technologie haut de gamme',
        'Prix significativement sous les PHEV européens équivalents',
      ],
      objections: [
        'Nécessite une borne de recharge à domicile pour profiter du PHEV',
        'Poids PHEV plus élevé (impact consommation thermique)',
      ],
      argument_prix: 'PHEV 5★ Euro-NCAP, écran 14,8", V2L, 1 200 km d\'autonomie — introuvable sous 47 000 € en Europe',
    },

    marche: {
      part_marche_cible: '0,7%',
      croissance_segment: '+18,5% en 2024 (PHEV SUV)',
      tendance: 'Le PHEV explose en entreprise pour l\'avantage fiscal. Les particuliers apprécient la flexibilité 100% élec / autonomie thermique.',
      risques: 'Droits de douane UE sur véhicules chinois. Infrastructure recharge à domicile requise.',
      opportunites: 'Gap de 8-12k€ vs concurrence européenne. CO₂ très bas = exonération malus + avantages fiscaux pro. Seul PHEV SUV D à ce prix.',
    },
  },
]

export function getProduct(id) {
  return PRODUCTS.find((p) => p.id === id)
}
